### ISSUE TITLE
pcsc_scan.exe finds readers but fails to present prompt

### ISSUE THREAD

**Issue by digitalentropy** [LudovicRousseau/pcsc-tools#34] opened 2020-02-28 21:47 UTC
I am observing an issue with pcsc_scan.exe detecting my readers and then looping over and over rather than presenting a prompt to select reader and action.

The issue is observed when compiling from scratch and also when using the pre-compiled Windows binary.

I've uploaded a log of the output I am observing in both scenarios.

[log.txt](https://github.com/LudovicRousseau/pcsc-tools/files/4269233/log.txt)

Any thoughts on possible causes?

**Comment by LudovicRousseau** [comment] 2020-02-29 09:24
Why do you expect a prompt to select a reader?

I agree the continuous loop is a bug somewhere.

**Comment by digitalentropy** [comment] 2020-02-29 15:47
I was expecting it only because of what the screenshots looked like.  It appeared that the system would list readers and then ask the user to select a reader to interrogate.

Apologies if that assumption is incorrect.

On Feb 29, 2020, at 3:24 AM, Ludovic Rousseau <notifications@github.com> wrote:

﻿

Why do you expect a prompt to select a reader?

I agree the continuous loop is a bug somewhere.

**Comment by LudovicRousseau** [comment] 2020-02-29 17:32
I can't reproduce the problem on my Windows 10.
Please apply this patch, rebuild and try again.
```patch
diff --git a/pcsc_scan.c b/pcsc_scan.c
index e054624..6e6b29c 100644
--- a/pcsc_scan.c
+++ b/pcsc_scan.c
@@ -630,6 +630,7 @@ get_readers:
    {
        time_t t;
 
+       printf("rv: 0x%08X\n", rv);
        if (pnp)
        {
 #ifdef WIN32
```

**Comment by digitalentropy** [comment] 2020-03-02 04:35
Current output is as follows:

```rv: 0x00000000
Scanning present readers...
0: Alcor Micro USB Smart Card Reader 0
1: JAVACOS Virtual Contact Reader 0
2: JAVACOS Virtual Contactless Reader 1
rv: 0x00000000
````
It still loops over and over, regardless of card state.

**Comment by LudovicRousseau** [comment] 2020-03-02 10:34
OK.
Try again with this new patch:
```patch
diff --git a/pcsc_scan.c b/pcsc_scan.c
index e054624..f231e14 100644
--- a/pcsc_scan.c
+++ b/pcsc_scan.c
@@ -635,6 +635,7 @@ get_readers:
 #ifdef WIN32
            /* check if the number of readers has changed */
            LONG newNbReaders = rgReaderStates_t[nbReaders-1].dwEventState >> 16;
+           printf("nbReaders: %d, .dwEventState: 0x%08X\n", nbReaders, rgReaderStates_t[nbReaders-1].dwEventState);
            if (newNbReaders + 1 != nbReaders)
 #else
            if (rgReaderStates_t[nbReaders-1].dwEventState &
```

**Comment by digitalentropy** [comment] 2020-03-02 19:24
New looping message:

```
Scanning present readers...
0: Alcor Micro USB Smart Card Reader 0
1: JAVACOS Virtual Contact Reader 0
2: JAVACOS Virtual Contactless Reader 1
nbReaders: 4, .dwEventState: 0x00040002
```

**Comment by LudovicRousseau** [comment] 2020-03-02 21:03
What version of Windows do you use?

**Comment by digitalentropy** [comment] 2020-03-02 21:33
Windows 10 (Current)

I can check exact version number when I get back.

**Comment by digitalentropy** [comment] 2020-03-03 01:42
Microsoft Windows [Version 10.0.18363.657]

**Comment by LudovicRousseau** [comment] 2020-03-07 10:27
Fixed in https://github.com/LudovicRousseau/pcsc-tools/commit/1727dbf217f22b6e32ad5c066989f542f6233da9

**Closed by LudovicRousseau** 2020-03-07 10:27 UTC

**Comment by LudovicRousseau** [comment] 2020-03-07 14:31
See also https://ludovicrousseau.blogspot.com/2020/03/better-pcscscan-on-windows.html
